### ISSUE TITLE
Can't roll damage for bombs

### ISSUE THREAD

**Issue by Dario-Rendon42** [Ediwir/pf2e-alchemyABP#1]
Foundry version: 9.269
PF2e version: 3.13.5.16
Only this module installed, no others.

I was using this module in my game to great success until recently. 
Now, my player cannot roll damage. The button for damage/critical does not work in the actions tab, nor do the damage/critical buttons in the chat popup work after rolling for attack.

When this happens, the developer console displays this message.
`Uncaught (in promise) Error: PF2e System | This weapon deals no damage`

**Comment by Ediwir** [comment]
Very annoying. A change in Core PF2 Foundry prevented the use of d0 weapons, which is how I had them work earlier - it's been "fixed", but now every bomb deals 1 extra damage.

It's not visually satisfying, but you should be able to use the module again. I'll see if I can find a better way later on.

Note that you'll need to reassign the bombs and bomb recipes to the character in order to get the updated version.

**Comment by Dario-Rendon42** [comment]
I appreciate the time you took to fix this. Rolling damage now works.

Though just to be precise, bombs seem to do +2 to +5 more damage than they should, which differs from the statement on your README.

Throwing moderate alchemist fire at lvl 1 has 2 bonus damage
![Screenshot 2022-09-17 000719](https://user-images.githubusercontent.com/26585078/190841474-37bb5667-69c3-4f6a-b58f-d7c9d67385cc.png)

Using the same bomb at level 20 we get similarly +5 bonus damage.
![Screenshot 2022-09-17 000955](https://user-images.githubusercontent.com/26585078/190841540-93f2d63a-39c6-4540-ba30-bb41472da8e3.png)

I understand that changes to the pf2e module probably make a fix to this impossible for the time being, I just wanted to make note of the difference..

Thanks again for providing a fix.

**Comment by Ediwir** [comment]
Ah, that's actually my mistake, I noticed it now. Damage used to be 0, which is no longer valid and got changed to 1d1, but there's another line that should have remained 0 and got lumped in with the change.

Yeah from what I can tell it can't be fixed right now, weapons cannot have negative damage modifiers (otherwise I'd have them apply a penalty based on level, like I did with drakeheart), but I can remove that extra +1.

As a side note, you can (if you want) give yourself a penalty to all bomb damage with a simple rule element. I might add it as an option if it helps. Should be able to work on this tomorrow.
